# Generated by Django 6.0.5 on 2026-05-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_horario',
            new_name='data',
        ),
    ]
