# Generated by Django 6.0.5 on 2026-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_data_horario_agendamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
