# Generated by Django 6.0.5 on 2026-06-07 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_normaluser_prestador_alter_agendamento_prestador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='user',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.DeleteModel(
            name='Prestador',
        ),
    ]
