# Generated by Django 6.0.5 on 2026-06-11 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_prestador_user_alter_agendamento_prestador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='prestador',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('hr_abertura', models.TimeField()),
                ('hr_fechamento', models.TimeField()),
                ('dc_estabelecimento', models.TextField()),
                ('endereco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.endereco')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='estabelecimento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.estabelecimento'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dc_evento', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('hr_inicio', models.TimeField()),
                ('hr_fim', models.TimeField()),
                ('estabelecimento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.evento')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='evento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.evento'),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dc_servico', models.TextField()),
                ('duracao', models.DurationField()),
                ('vl_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estabelecimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.estabelecimento')),
                ('evento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.evento')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.servico'),
        ),
    ]
