# Generated by Django 6.0.5 on 2026-06-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_endereco_rename_prestador_agendamento_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='endereco_id',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='user_id',
            new_name='user',
        ),
    ]
