# Generated by Django 6.0.5 on 2026-06-15 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_rename_endereco_id_estabelecimento_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='agenda.endereco'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
