# Generated by Django 6.0.5 on 2026-06-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_estabelecimento_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='estabelecimento_id',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='servico_id',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='estabelecimento_id',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='estabelecimento_id',
            new_name='estabelecimento',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='evento_id',
            new_name='evento',
        ),
    ]
