# Generated by Django 6.0.5 on 2026-06-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_rename_estabelecimento_id_agendamento_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='agenda.servico'),
        ),
    ]
