# Generated by Django 6.0.5 on 2026-06-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_agendamento_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='estabelecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.estabelecimento'),
        ),
    ]
